const OpenFoodFactsService = require('../services/OpenFoodFactsService');
const geminiService = require('../services/geminiService');
const FoodCache = require('../models/FoodCache');

/**
 * GET /food/barcode/:code
 */
const getByBarcode = async (req, res, next) => {
  try {
    const { code } = req.params;

    if (!code || code.length < 4) {
      return res.status(400).json({
        success: false,
        message: 'Invalid barcode.',
      });
    }

    const result = await OpenFoodFactsService.fetchByBarcode(code);

    if (!result) {
      console.log('Product not found in OpenFoodFacts, falling back to Gemini API...');
      const geminiFood = await geminiService.fetchProductFallback(code);
      
      if (geminiFood) {
        let additivesAnalysis = [];
        try {
          additivesAnalysis = await geminiService.analyzeAdditives(geminiFood.ingredientsList, geminiFood.additives);
        } catch (err) {
          console.error('Failed to parse additives for gemini fallback', err);
        }

        const newFood = new FoodCache({
          barcode: code,
          productName: geminiFood.productName || 'Unknown AI Product',
          brands: geminiFood.brands || 'Unknown',
          ingredientsList: geminiFood.ingredientsList || '',
          nutrients: geminiFood.nutrients || {},
          additives: geminiFood.additives || [],
          additivesDetails: additivesAnalysis,
          isAdditivesAnalyzed: true,
          novaGroup: geminiFood.novaGroup || null,
          nutriScore: geminiFood.nutriScore || null,
          source: 'ai-generated'
        });
        await newFood.save();
        
        return res.json({
          success: true,
          data: {
            source: 'ai-generated',
            product: newFood,
          },
        });
      }

      return res.status(404).json({
        success: false,
        message: 'Product not found. Try searching by name instead or could not be generated by AI.',
      });
    }

    // Check if we need to analyze additives for OFF food
    let dbFood = await FoodCache.findOne({ barcode: code });
    if (dbFood && !dbFood.isAdditivesAnalyzed) {
      try {
        const additivesAnalysis = await geminiService.analyzeAdditives(dbFood.ingredientsList, dbFood.additives);
        dbFood.additivesDetails = additivesAnalysis;
        dbFood.isAdditivesAnalyzed = true;
        await dbFood.save();
        
        result.product = dbFood;
      } catch (err) {
        console.error('Failed to analyze additives for OFF product', err);
      }
    }

    res.json({
      success: true,
      data: {
        source: result.source,
        product: result.product,
      },
    });
  } catch (error) {
    next(error);
  }
};

/**
 * GET /food/search?q=product_name&page=1
 */
const search = async (req, res, next) => {
  try {
    const { q, page = 1 } = req.query;

    if (!q || q.trim().length === 0) {
      return res.status(400).json({
        success: false,
        message: 'Search query is required.',
      });
    }

    const result = await OpenFoodFactsService.searchProducts(q.trim(), parseInt(page));

    res.json({
      success: true,
      data: result,
    });
  } catch (error) {
    next(error);
  }
};

/**
 * POST /food/manual
 * Body: { description: 'string' }
 */
const createManualProduct = async (req, res, next) => {
  try {
    const { description } = req.body;

    if (!description || description.trim().length === 0) {
      return res.status(400).json({
        success: false,
        message: 'Product description is required.',
      });
    }

    // Call Gemini to parse
    const geminiFood = await geminiService.parseManualProduct(description.trim());
    if (!geminiFood) {
      return res.status(400).json({
        success: false,
        message: 'Could not understand the food description. Please be more specific.',
      });
    }

    // Fuzzy check for existing product to avoid duplicates
    const existingFood = await FoodCache.findOne({ 
      productName: { $regex: new RegExp(`^${geminiFood.productName}$`, 'i') },
      source: 'ai-generated'
    });

    if (existingFood) {
      return res.json({
        success: true,
        data: {
          source: 'ai-generated',
          product: existingFood,
        },
      });
    }

    // Create a pseudo barcode
    const pseudoBarcode = `MANUAL-${Date.now()}-${Math.floor(Math.random() * 1000)}`;

    let additivesAnalysis = [];
    try {
      additivesAnalysis = await geminiService.analyzeAdditives(geminiFood.ingredientsList, geminiFood.additives);
    } catch (err) {
      console.error('Failed to parse additives for manual product', err);
    }

    const newFood = new FoodCache({
      barcode: pseudoBarcode,
      productName: geminiFood.productName || 'Unknown AI Product',
      brands: geminiFood.brands || 'Unknown',
      ingredientsList: geminiFood.ingredientsList || '',
      nutrients: geminiFood.nutrients || {},
      additives: geminiFood.additives || [],
      additivesDetails: additivesAnalysis,
      isAdditivesAnalyzed: true,
      novaGroup: geminiFood.novaGroup || null,
      nutriScore: geminiFood.nutriScore || null,
      source: 'ai-generated'
    });

    await newFood.save();

    res.status(201).json({
      success: true,
      data: {
        source: 'ai-generated',
        product: newFood,
      },
    });
  } catch (error) {
    next(error);
  }
};

module.exports = { getByBarcode, search, createManualProduct };
